global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'discord-webhook'

receivers:
- name: 'discord-webhook'
  webhook_configs:
  - url: 'https://discord.com/api/webhooks/1235474143961415720/--mlQoNH1yjpaEpSz6lbdWflShaSVHIJUDAXKxZ1wHIKNGLrqEXMdupBHCbHvCX-nE6D'
    send_resolved: true

templates:
- '/etc/alertmanager/template/*.tmpl'
